// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR4xfufsGxm_nsNKwXTH8_VTeHbKZvJzo',
    appId: '1:803095632209:web:55f0a6d8bdf71298b81b70',
    messagingSenderId: '803095632209',
    projectId: 'flutter-7a6ad',
    authDomain: 'flutter-7a6ad.firebaseapp.com',
    storageBucket: 'flutter-7a6ad.appspot.com',
    measurementId: 'G-9ZKSBYFKCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALyxHZ8jNRRLiUNOWdtp2Ud-PkcKY3MWk',
    appId: '1:803095632209:android:a8cd4855c7c74174b81b70',
    messagingSenderId: '803095632209',
    projectId: 'flutter-7a6ad',
    storageBucket: 'flutter-7a6ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWTHGLSRUACdJmlzJ2_ZRgsMuk4gXGgho',
    appId: '1:803095632209:ios:a2fa845a149f2cb1b81b70',
    messagingSenderId: '803095632209',
    projectId: 'flutter-7a6ad',
    storageBucket: 'flutter-7a6ad.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWTHGLSRUACdJmlzJ2_ZRgsMuk4gXGgho',
    appId: '1:803095632209:ios:22da5a201df8b929b81b70',
    messagingSenderId: '803095632209',
    projectId: 'flutter-7a6ad',
    storageBucket: 'flutter-7a6ad.appspot.com',
    iosBundleId: 'com.example.spotify.RunnerTests',
  );
}
